### ISSUE TITLE
Add 'Output' in the docstring of predict functions

### ISSUE THREAD

**Issue by grantgasser** [NUCS349/hw2-decision-trees#16]
Docstring of predict functions in Decision Tree and Prior Probability class lacks an 'Output' section. It currently unclear whether the students should return anything from the function. If they are to return something, which data type, and what should the variable contain?

I would be willing to add this, with variable `predictions` being a `np.array` and that it is supposed to contain the models predictions given the new data.

I know this issue is somewhat trivial but I'd like to do this to practice collaborating on GitHub. Do I need to be given authorization to create branches and create pull requests?

**Comment by zezhu2022** [comment]
resolved
