### ISSUE TITLE
change `load_data()` docstring to ask for appropriate 1xN targets array

### ISSUE THREAD

**Issue by ascourtas** [NUCS349/hw2-decision-trees#19]
In `load_data()`, the docstring says the function shall return "targets (np.array): numpy array of size Nx1 containing the 1 feature." Thus, we'd be expected to return an array with N rows and 1 column. However, what is actually tested for in `test_load_data()` is a numpy array of size 1xN, with 1 row and N columns (the `targets` variable, which is compared to `load_data()`'s `_targets`). The docstring should be updated to reflect this.

**Comment by marcelbonnici** [comment]
Ran into this struggle several hours ago. Agreed!

**Comment by zezhu2022** [comment]
resolved
